### ISSUE TITLE
Crash to desktop if I attempt to use jump select while controlling a CTC

### ISSUE THREAD

**Issue by ForgetfulJones** [Allen-Wrench/JumpSelector#3]
While controlling a CTC, I attempted to open the jump select dialog, crash resulted.  Sure, you can't actually do anything else while controlling a ctc anyways, but the crash is probably not intended.
(Incidently, thanks for your mod, I use it all the time.)

**Comment by Allen-Wrench** [comment]
No, a crash is definitely not supposed to happen, I'll look into it. Thanks for the heads up.

Ideally, you should only be able to use the jump select action in cases where you would be able to use the vanilla jump mechanic. So if you can initiate a jump while controlling a CTC, then i'll make sure that its possible to use jump selector in that case.

**Comment by Allen-Wrench** [comment]
Alright, fixed the crash and also added better support for the custom turret controller. Now when performing a blind jump while controlling the CTC, it will jump in the direction you are aiming ;)

Ill submit the update to the plugin hub, so the update should be live by tomorrow hopefully.
