### ISSUE TITLE
Plugin can not be loaded in dedicated Server

### ISSUE THREAD

**Issue by me777** [Allen-Wrench/JumpSelector#4]
When I add and open the plugin.dll the dedicated server givers this error and doesn't load it.

Can you please look into it and fix it?

Thanks a lot, this plugin is really great in singleplayer but I wanted to make a server...

![grafik](https://github.com/Allen-Wrench/JumpSelector/assets/13494916/44138219-39c5-4129-8fcf-b46e8eae5d5a)
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at VRage.Dedicated.Configurator.PluginManagementControl.ProcessAssembly(String file, PluginAssembly& pluginAssembly)
   at VRage.Dedicated.Configurator.PluginManagementControl.<btnAddAssembly_Click>b__14_0(FileDialogEventArgs result)
   at System.DelegateExtensions.InvokeIfNotNull[T1](Action`1 handler, T1 arg1)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4729.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SpaceEngineersDedicated
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/SpaceEngineersDedicated.exe
----------------------------------------
Sandbox.Game
    Assembly Version: 0.1.1.0
    Win32 Version: 0.1.1
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/Sandbox.Game.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
VRage.Library
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/VRage.Library.DLL
----------------------------------------
SpaceEngineers.Game
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/SpaceEngineers.Game.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4718.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
VRage.Math
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/VRage.Math.DLL
----------------------------------------
VRage
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/VRage.DLL
----------------------------------------
VRage.Render
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/VRage.Render.DLL
----------------------------------------
VRage.Game
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/VRage.Game.DLL
----------------------------------------
VRage.Dedicated
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/VRage.Dedicated.DLL
----------------------------------------
Sandbox.Graphics
    Assembly Version: 0.1.1.0
    Win32 Version: 0.1.1
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/Sandbox.Graphics.DLL
----------------------------------------
VRage.Input
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/VRage.Input.DLL
----------------------------------------
System.Collections.Immutable
    Assembly Version: 1.2.3.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/System.Collections.Immutable.DLL
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4654.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
VRage.Platform.Windows
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/VRage.Platform.Windows.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.0
    Win32 Version: 4.6.27129.04
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/System.Memory.DLL
----------------------------------------
HavokWrapper
    Assembly Version: 0.1.1.0
    Win32 Version: 0.1.1
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/HavokWrapper.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4729.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
VRage.Game.XmlSerializers
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/VRage.Game.XmlSerializers.DLL
----------------------------------------
ProtoBuf.Net.Core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/ProtoBuf.Net.Core.DLL
----------------------------------------
VRage.Network
    Assembly Version: 1.0.53.0
    Win32 Version: 1.0.53.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/VRage.Network.DLL
----------------------------------------
System.ComponentModel.Annotations
    Assembly Version: 4.2.1.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/System.ComponentModel.Annotations.DLL
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
VRage.Scripting
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/VRage.Scripting.DLL
----------------------------------------
SharpDX.DXGI
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.1
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/SharpDX.DXGI.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
SharpDX
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.1
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/SharpDX.DLL
----------------------------------------
System.Threading
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Threading/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.dll
----------------------------------------
System.Collections
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll
----------------------------------------
RestSharp
    Assembly Version: 106.6.10.0
    Win32 Version: 106.6.10.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/RestSharp.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4729.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
VRage.Ansel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/VRage.Ansel.DLL
----------------------------------------
ProtoBuf.Net
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/ProtoBuf.Net.DLL
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Reflection.Emit.Lightweight/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Reflection.Emit.ILGeneration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4435.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.ServiceProcess
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceProcess/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ServiceProcess.dll
----------------------------------------
SpaceEngineers.ObjectBuilders
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/SpaceEngineers.ObjectBuilders.DLL
----------------------------------------
Sandbox.Common
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/Sandbox.Common.DLL
----------------------------------------
EmptyKeys.UserInterface
    Assembly Version: 3.2.0.0
    Win32 Version: 3.2.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/EmptyKeys.UserInterface.DLL
----------------------------------------
EmptyKeys.UserInterface.Core
    Assembly Version: 3.2.0.0
    Win32 Version: 3.2.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/EmptyKeys.UserInterface.Core.DLL
----------------------------------------
Sandbox.RenderDirect
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/Sandbox.RenderDirect.DLL
----------------------------------------
VRage.NativeWrapper
    Assembly Version: 0.1.1.0
    Win32 Version: 0.1.1
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/VRage.NativeWrapper.DLL
----------------------------------------
SpaceEngineers.ObjectBuilders.XmlSerializers
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/SpaceEngineers.ObjectBuilders.XmlSerializers.DLL
----------------------------------------
Sandbox.Game.XmlSerializers
    Assembly Version: 0.1.1.0
    Win32 Version: 0.1.1.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/Sandbox.Game.XmlSerializers.DLL
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
VRage.RemoteClient.Core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/servers/spaceengineers/DedicatedServer64/VRage.RemoteClient.Core.DLL
----------------------------------------
System.Windows.Forms.DataVisualization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.DataVisualization/v4.0_4.0.0.0__31bf3856ad364e35/System.Windows.Forms.DataVisualization.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
FPSCounter_vvgynib5.15l
    Assembly Version: 1.1.6.0
    Win32 Version: 
    CodeBase: file:///C:/servers/spaceengineers/Plugins/GitHub/WesternGamer/FPSCounter/plugin.dll
----------------------------------------
No_News_Plugin_m2lfvbb3.5qo
    Assembly Version: 1.0.1.0
    Win32 Version: 
    CodeBase: file:///C:/servers/spaceengineers/Plugins/GitHub/WesternGamer/No-News-Plugin/plugin.dll
----------------------------------------
RemoveIntroVideoPlugin_a1ovgjda.v4a
    Assembly Version: 1.1.1.0
    Win32 Version: 
    CodeBase: file:///C:/servers/spaceengineers/Plugins/GitHub/WesternGamer/RemoveIntroVideoPlugin/plugin.dll
----------------------------------------
MorePPSettings_a1mpwlag.rp2
    Assembly Version: 1.0.0.0
    Win32 Version: 
    CodeBase: file:///C:/servers/spaceengineers/Plugins/GitHub/Math0424/MorePPSettings/plugin.dll
----------------------------------------
SE_PreventBlockResize_azhgthl0.lnm
    Assembly Version: 1.0.0.0
    Win32 Version: 
    CodeBase: file:///C:/servers/spaceengineers/Plugins/GitHub/bcmpinc/SE-PreventBlockResize/plugin.dll
----------------------------------------
NoArmorEdges_tpssayoa.4hc
    Assembly Version: 1.0.0.0
    Win32 Version: 
    CodeBase: file:///C:/servers/spaceengineers/Plugins/GitHub/austinvaness/NoArmorEdges/plugin.dll
----------------------------------------
JumpSelector_yr3b1ijw.yit
    Assembly Version: 1.0.0.7
    Win32 Version: 
    CodeBase: file:///C:/servers/spaceengineers/Plugins/GitHub/Allen-Wrench/JumpSelector/plugin.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.`

**Comment by Allen-Wrench** [comment]
Sorry for the late reply, for some reason I didn't see the email when you opened this issue. 

This is not designed to be used on a server, its only a client side plugin. I may at some point make a mod that can do something similar so that a server can add it and players wouldn't have to use a plugin.

The only reason I haven't done so already is that it would require me to re-create the UI using one of the UI mods, which I'm not super motivated to do... But maybe one day.
